### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np
import random

In [3]:
# 1

vector = np.array([random.uniform(0, 1) for _ in range(10)])

In [4]:
print(vector)
print(vector.shape)

[0.663129   0.44909211 0.13605845 0.08982536 0.93823456 0.30080009
 0.83776079 0.52841468 0.31794827 0.11026493]
(10,)


In [5]:
# альтернативний спосіб

vector = np.random.rand(10)

In [6]:
print(vector)
print(vector.shape)

[0.51087989 0.31204185 0.75910149 0.57147925 0.93560302 0.44109341
 0.08792369 0.35759087 0.5384264  0.34223438]
(10,)


In [7]:
# 2

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

In [8]:
print(matrix)
print(matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]]
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [9]:
# 1

vector = np.round(vector + 10, 2)
print("Vector + 10 (rounded):\n", vector)

Vector + 10 (rounded):
 [10.51 10.31 10.76 10.57 10.94 10.44 10.09 10.36 10.54 10.34]


In [10]:
# 2

matrix = matrix * 2
print("Matrix * 2:\n", matrix)

Matrix * 2:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]


In [11]:
# 3

vector_squared = np.square(vector)
print("Vector squared:\n", vector_squared)

Vector squared:
 [110.4601 106.2961 115.7776 111.7249 119.6836 108.9936 101.8081 107.3296
 111.0916 106.9156]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [12]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [15]:
# 1

result_matrix = np.dot(B, A)
print("Result Matrix (A * B):\n", result_matrix)
print("Result Matrix Shape:", result_matrix.shape)

Result Matrix (A * B):
 [[0.7281 0.5202]
 [0.2034 0.2846]]
Result Matrix Shape: (2, 2)


In [16]:
# 2

result_C = np.dot(result_matrix, C)
print("Result Matrix * C:\n", result_C)
print("Result Matrix Shape:", result_C.shape)

Result Matrix * C:
 [[0.5202]
 [0.2846]]
Result Matrix Shape: (2, 1)


In [17]:
# 3

result_D = np.dot(result_matrix, D)
print("Result Matrix * D:\n", result_D)
print("Result Matrix Shape:", result_D.shape)

Result Matrix * D:
 [[0.5202 0.7281]
 [0.2846 0.2034]]
Result Matrix Shape: (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [18]:
# 1

result_matrix_T = result_matrix.T
print("Transposed Result Matrix:\n", result_matrix_T)

Transposed Result Matrix:
 [[0.7281 0.2034]
 [0.5202 0.2846]]


In [19]:
# 2

vector_T = vector.T
print("Original vector shape:", vector.shape)
print("Transposed vector shape:", vector_T.shape)

Original vector shape: (10,)
Transposed vector shape: (10,)


In [20]:
# 3

column_vector = np.expand_dims(vector, axis=1)
print("Column vector:\n", column_vector)
print("Column vector shape:", column_vector.shape)

Column vector:
 [[10.51]
 [10.31]
 [10.76]
 [10.57]
 [10.94]
 [10.44]
 [10.09]
 [10.36]
 [10.54]
 [10.34]]
Column vector shape: (10, 1)


In [21]:
# 4

transposed_column = column_vector.T
print("Transposed column vector:\n", transposed_column)
print("Shape after transpose:", transposed_column.shape)

Transposed column vector:
 [[10.51 10.31 10.76 10.57 10.94 10.44 10.09 10.36 10.54 10.34]]
Shape after transpose: (1, 10)
